[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"

[dependencies]
shared = { path = "../shared" }
avian2d.workspace = true
bevy.workspace = true
lightyear.workspace = true
clap.workspace = true

async-compat = "0.2.4"
